name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          # 时间线
          SHOW_LOC_CHART: "True"
          # OS
          SHOW_OS: "False"
          # 项目
          SHOW_PROJECTS: "False"
          # 时区
          SHOW_TIMEZONE: "False"
          # 编辑器
          SHOW_EDITORS: "False"
          # 主页访问
          SHOW_PROFILE_VIEWS: "False"
          # GitHub Data
          SHOW_SHORT_INFO: "False"
          # Commits per day of week 
          SHOW_DAYS_OF_WEEK: "False"
          
